default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jumanji-api_development
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: jumanji-api_test
  username: postgres
  password:
  host: db

production:
  <<: *default
  database: jumanji-api_production
  host: <%= ENV['DATABASE_URL'] %>
